version: "3.8"

services:
  test: &default
    image: node:12
    working_dir: /app/
    command: "yarn test"
    environment:
      - APP_PORT=3333
    volumes:
      - .:/app

  install:
    <<: *default
    command: "yarn"

  app: &app
    <<: *default
    command: "yarn dev"
    container_name: iupp_node_api
    networks:
      frontend:
          ipv4_address: 172.19.0.2
    ports:
      - 3333:3333

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.19.0.0/24