version: "3.8"

services:
  test: &default
    image: node:12
    working_dir: /app/
    command: "yarn test"
    environment:
      - APP_DOMAIN=http://localhost
      - APP_PORT=3333
    volumes:
      - .:/app

  install:
    <<: *default
    command: "yarn"

  app: &app
    <<: *default
    command: "yarn start"
    container_name: iupp_node_api
    ports:
      - 3333:3333